# Generated by Django 4.1.1 on 2022-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=200)),
                ('assetCategory', models.CharField(max_length=200)),
                ('assetQuantity', models.FloatField(max_length=200)),
                ('assetPrice', models.FloatField(max_length=200)),
                ('assetTotal', models.FloatField(max_length=200)),
                ('assetDetails', models.CharField(max_length=500)),
            ],
        ),
    ]
